// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ETA.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ETA.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Title_Settings {
            get {
                return ResourceManager.GetString("Title_Settings", resourceCulture);
            }
        }
        
        public static string Max_Capacity {
            get {
                return ResourceManager.GetString("Max_Capacity", resourceCulture);
            }
        }
        
        public static string Warn_Capacity {
            get {
                return ResourceManager.GetString("Warn_Capacity", resourceCulture);
            }
        }
        
        public static string Connection_URL {
            get {
                return ResourceManager.GetString("Connection_URL", resourceCulture);
            }
        }
        
        public static string TestConnection {
            get {
                return ResourceManager.GetString("TestConnection", resourceCulture);
            }
        }
        
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        public static string DeleteHistory {
            get {
                return ResourceManager.GetString("DeleteHistory", resourceCulture);
            }
        }
        
        public static string Contributions {
            get {
                return ResourceManager.GetString("Contributions", resourceCulture);
            }
        }
        
        public static string Title_Supplies {
            get {
                return ResourceManager.GetString("Title_Supplies", resourceCulture);
            }
        }
        
        public static string Title_Statistics {
            get {
                return ResourceManager.GetString("Title_Statistics", resourceCulture);
            }
        }
        
        public static string TotalConsumptionInTimespan {
            get {
                return ResourceManager.GetString("TotalConsumptionInTimespan", resourceCulture);
            }
        }
        
        public static string AverageConsumptionInTimespan {
            get {
                return ResourceManager.GetString("AverageConsumptionInTimespan", resourceCulture);
            }
        }
        
        public static string OutOfSuppliesDate {
            get {
                return ResourceManager.GetString("OutOfSuppliesDate", resourceCulture);
            }
        }
        
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        public static string Title_Messages {
            get {
                return ResourceManager.GetString("Title_Messages", resourceCulture);
            }
        }
        
        public static string LoadingConfiguration {
            get {
                return ResourceManager.GetString("LoadingConfiguration", resourceCulture);
            }
        }
        
        public static string SavingConfiguration {
            get {
                return ResourceManager.GetString("SavingConfiguration", resourceCulture);
            }
        }
        
        public static string ReallyDeleteSuppliesHistory {
            get {
                return ResourceManager.GetString("ReallyDeleteSuppliesHistory", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string DeletingData {
            get {
                return ResourceManager.GetString("DeletingData", resourceCulture);
            }
        }
        
        public static string TestingConnection {
            get {
                return ResourceManager.GetString("TestingConnection", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string ConnectivityTestFailedVerifyUrlAndPort {
            get {
                return ResourceManager.GetString("ConnectivityTestFailedVerifyUrlAndPort", resourceCulture);
            }
        }
        
        public static string ConnectivityTestSuccessfulConfigSaved {
            get {
                return ResourceManager.GetString("ConnectivityTestSuccessfulConfigSaved", resourceCulture);
            }
        }
        
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        public static string LoadingWarningLevel {
            get {
                return ResourceManager.GetString("LoadingWarningLevel", resourceCulture);
            }
        }
        
        public static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        public static string ConfigureSettingsFirst {
            get {
                return ResourceManager.GetString("ConfigureSettingsFirst", resourceCulture);
            }
        }
        
        public static string AllData {
            get {
                return ResourceManager.GetString("AllData", resourceCulture);
            }
        }
        
        public static string UpdatingStatistics {
            get {
                return ResourceManager.GetString("UpdatingStatistics", resourceCulture);
            }
        }
        
        public static string NotEnoughData {
            get {
                return ResourceManager.GetString("NotEnoughData", resourceCulture);
            }
        }
        
        public static string NoCalculationPossible {
            get {
                return ResourceManager.GetString("NoCalculationPossible", resourceCulture);
            }
        }
        
        public static string Initializing {
            get {
                return ResourceManager.GetString("Initializing", resourceCulture);
            }
        }
        
        public static string UpdatingMessages {
            get {
                return ResourceManager.GetString("UpdatingMessages", resourceCulture);
            }
        }
    }
}
